#!/bin/sh

if [ ! -f /etc/periodic/daily/amclean_update ]; then
  ln -s /usr/bin/amclean_update.py /etc/periodic/daily/amclean_update
  sed -i "s/^0\t2/$((RANDOM%61))\t$((RANDOM%9))/" /etc/crontabs/root
fi
/usr/sbin/clamd
/usr/bin/amclean.py $@
